name: Multi Docker
on:
  push:
    branches:
      - master
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true test npm test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t numbbbbb/multi-client ./client
      - run: docker build -t numbbbbb/multi-api ./server
      - run: docker build -t numbbbbb/multi-nginx ./nginx
      - run: docker build -t numbbbbb/multi-worker ./worker
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push numbbbbb/multi-client
      - run: docker push numbbbbb/multi-api
      - run: docker push numbbbbb/multi-nginx
      - run: docker push numbbbbb/multi-worker
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-2-590690859319
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: docker-compose.yml